module.exports = [
  {
    title: "Tyrannosaurus Rex",
    bookimage: "",
    humanwritten: false,
    author: "North America",
    story: "28",
  },
  {
    title: "Blue Whale",
    bookimage: "",
    humanwritten: false,
    author: "Global",
    story: 90,
  },
  {
    title: "Woolly Mammoth",
    bookimage: "",
    humanwritten: false,
    author: "Eurasia",
    story: 60,
  },
  {
    title: "Bengal Tiger",
    bookimage: "",
    humanwritten: false,
    author: "India",
    story: 10,
  },
  {
    title: "Giant Squid",
    bookimage: "",
    humanwritten: false,
    author: "Global",
    story: 5,
  },
  {
    title: "Gorilla",
    bookimage: "",
    humanwritten: false,
    author: "Africa",
    story: 35,
  },
  {
    title: "Dodo",
    bookimage: "",
    humanwritten: false,
    author: "Mauritius",
    story: 20,
  },
  {
    title: "Kakapo",
    bookimage: "",
    humanwritten: false,
    author: "New Zealand",
    story: 90,
  },
  {
    title: "Red Panda",
    bookimage: "",
    humanwritten: false,
    author: "Himalayas",
    story: 14,
  },

  {
    title: "Snow Leopard",
    bookimage: "",
    humanwritten: false,
    author: "Central Asia",
    story: 10,
  },
];
